package com.aj.sendall.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.aj.sendall.db.model.Connections;
import com.aj.sendall.db.model.PersonalInteraction;

import com.aj.sendall.db.dao.ConnectionsDao;
import com.aj.sendall.db.dao.PersonalInteractionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig connectionsDaoConfig;
    private final DaoConfig personalInteractionDaoConfig;

    private final ConnectionsDao connectionsDao;
    private final PersonalInteractionDao personalInteractionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        connectionsDaoConfig = daoConfigMap.get(ConnectionsDao.class).clone();
        connectionsDaoConfig.initIdentityScope(type);

        personalInteractionDaoConfig = daoConfigMap.get(PersonalInteractionDao.class).clone();
        personalInteractionDaoConfig.initIdentityScope(type);

        connectionsDao = new ConnectionsDao(connectionsDaoConfig, this);
        personalInteractionDao = new PersonalInteractionDao(personalInteractionDaoConfig, this);

        registerDao(Connections.class, connectionsDao);
        registerDao(PersonalInteraction.class, personalInteractionDao);
    }
    
    public void clear() {
        connectionsDaoConfig.clearIdentityScope();
        personalInteractionDaoConfig.clearIdentityScope();
    }

    public ConnectionsDao getConnectionsDao() {
        return connectionsDao;
    }

    public PersonalInteractionDao getPersonalInteractionDao() {
        return personalInteractionDao;
    }

}
