package com.aj.sendall.db.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.aj.sendall.db.converters.FileStatusToIntConverter;
import com.aj.sendall.db.enums.FileStatus;

import com.aj.sendall.db.model.PersonalInteraction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSONAL_INTERACTION".
*/
public class PersonalInteractionDao extends AbstractDao<PersonalInteraction, Long> {

    public static final String TABLENAME = "PERSONAL_INTERACTION";

    /**
     * Properties of entity PersonalInteraction.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PersonalInteractionId = new Property(0, Long.class, "personalInteractionId", true, "PERSONAL_INTERACTION_ID");
        public final static Property ConnectionId = new Property(1, Long.class, "connectionId", false, "CONNECTION_ID");
        public final static Property FileUri = new Property(2, String.class, "fileUri", false, "FILE_URI");
        public final static Property MediaType = new Property(3, Integer.class, "mediaType", false, "MEDIA_TYPE");
        public final static Property FileStatus = new Property(4, Integer.class, "fileStatus", false, "FILE_STATUS");
        public final static Property ModifiedTime = new Property(5, java.util.Date.class, "modifiedTime", false, "MODIFIED_TIME");
        public final static Property FileName = new Property(6, String.class, "fileName", false, "FILE_NAME");
        public final static Property FileSize = new Property(7, String.class, "fileSize", false, "FILE_SIZE");
    }

    private final FileStatusToIntConverter fileStatusConverter = new FileStatusToIntConverter();
    private Query<PersonalInteraction> connections_PersonalIntersQuery;

    public PersonalInteractionDao(DaoConfig config) {
        super(config);
    }
    
    public PersonalInteractionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSONAL_INTERACTION\" (" + //
                "\"PERSONAL_INTERACTION_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: personalInteractionId
                "\"CONNECTION_ID\" INTEGER," + // 1: connectionId
                "\"FILE_URI\" TEXT," + // 2: fileUri
                "\"MEDIA_TYPE\" INTEGER," + // 3: mediaType
                "\"FILE_STATUS\" INTEGER," + // 4: fileStatus
                "\"MODIFIED_TIME\" INTEGER," + // 5: modifiedTime
                "\"FILE_NAME\" TEXT," + // 6: fileName
                "\"FILE_SIZE\" TEXT);"); // 7: fileSize
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSONAL_INTERACTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PersonalInteraction entity) {
        stmt.clearBindings();
 
        Long personalInteractionId = entity.getPersonalInteractionId();
        if (personalInteractionId != null) {
            stmt.bindLong(1, personalInteractionId);
        }
 
        Long connectionId = entity.getConnectionId();
        if (connectionId != null) {
            stmt.bindLong(2, connectionId);
        }
 
        String fileUri = entity.getFileUri();
        if (fileUri != null) {
            stmt.bindString(3, fileUri);
        }
 
        Integer mediaType = entity.getMediaType();
        if (mediaType != null) {
            stmt.bindLong(4, mediaType);
        }
 
        FileStatus fileStatus = entity.getFileStatus();
        if (fileStatus != null) {
            stmt.bindLong(5, fileStatusConverter.convertToDatabaseValue(fileStatus));
        }
 
        java.util.Date modifiedTime = entity.getModifiedTime();
        if (modifiedTime != null) {
            stmt.bindLong(6, modifiedTime.getTime());
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(7, fileName);
        }
 
        String fileSize = entity.getFileSize();
        if (fileSize != null) {
            stmt.bindString(8, fileSize);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PersonalInteraction entity) {
        stmt.clearBindings();
 
        Long personalInteractionId = entity.getPersonalInteractionId();
        if (personalInteractionId != null) {
            stmt.bindLong(1, personalInteractionId);
        }
 
        Long connectionId = entity.getConnectionId();
        if (connectionId != null) {
            stmt.bindLong(2, connectionId);
        }
 
        String fileUri = entity.getFileUri();
        if (fileUri != null) {
            stmt.bindString(3, fileUri);
        }
 
        Integer mediaType = entity.getMediaType();
        if (mediaType != null) {
            stmt.bindLong(4, mediaType);
        }
 
        FileStatus fileStatus = entity.getFileStatus();
        if (fileStatus != null) {
            stmt.bindLong(5, fileStatusConverter.convertToDatabaseValue(fileStatus));
        }
 
        java.util.Date modifiedTime = entity.getModifiedTime();
        if (modifiedTime != null) {
            stmt.bindLong(6, modifiedTime.getTime());
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(7, fileName);
        }
 
        String fileSize = entity.getFileSize();
        if (fileSize != null) {
            stmt.bindString(8, fileSize);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PersonalInteraction readEntity(Cursor cursor, int offset) {
        PersonalInteraction entity = new PersonalInteraction( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // personalInteractionId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // connectionId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fileUri
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // mediaType
            cursor.isNull(offset + 4) ? null : fileStatusConverter.convertToEntityProperty(cursor.getInt(offset + 4)), // fileStatus
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // modifiedTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fileName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // fileSize
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PersonalInteraction entity, int offset) {
        entity.setPersonalInteractionId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setConnectionId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setFileUri(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMediaType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setFileStatus(cursor.isNull(offset + 4) ? null : fileStatusConverter.convertToEntityProperty(cursor.getInt(offset + 4)));
        entity.setModifiedTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setFileName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFileSize(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PersonalInteraction entity, long rowId) {
        entity.setPersonalInteractionId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PersonalInteraction entity) {
        if(entity != null) {
            return entity.getPersonalInteractionId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PersonalInteraction entity) {
        return entity.getPersonalInteractionId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "personalInters" to-many relationship of Connections. */
    public List<PersonalInteraction> _queryConnections_PersonalInters(Long connectionId) {
        synchronized (this) {
            if (connections_PersonalIntersQuery == null) {
                QueryBuilder<PersonalInteraction> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ConnectionId.eq(null));
                connections_PersonalIntersQuery = queryBuilder.build();
            }
        }
        Query<PersonalInteraction> query = connections_PersonalIntersQuery.forCurrentThread();
        query.setParameter(0, connectionId);
        return query.list();
    }

}
