package com.aj.sendall.db.model;

import com.aj.sendall.db.enums.FileStatus;

import org.greenrobot.greendao.annotation.Convert;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSONAL_INTERACTION".
 */
@Entity
public class PersonalInteraction {

    @Id(autoincrement = true)
    private Long personalInteractionId;
    private long connectionId;

    @NotNull
    private String fileUri;

    @NotNull
    private String filePath;
    private int mediaType;

    @Convert(converter = com.aj.sendall.db.converters.FileStatusToIntConverter.class, columnType = Integer.class)
    private FileStatus fileStatus;

    @NotNull
    private java.util.Date modifiedTime;

    @NotNull
    private String fileName;
    private Long fileSize;
    private Long bytesTransfered;

    @Generated
    public PersonalInteraction() {
    }

    public PersonalInteraction(Long personalInteractionId) {
        this.personalInteractionId = personalInteractionId;
    }

    @Generated
    public PersonalInteraction(Long personalInteractionId, long connectionId, String fileUri, String filePath, int mediaType, FileStatus fileStatus, java.util.Date modifiedTime, String fileName, Long fileSize, Long bytesTransfered) {
        this.personalInteractionId = personalInteractionId;
        this.connectionId = connectionId;
        this.fileUri = fileUri;
        this.filePath = filePath;
        this.mediaType = mediaType;
        this.fileStatus = fileStatus;
        this.modifiedTime = modifiedTime;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.bytesTransfered = bytesTransfered;
    }

    public Long getPersonalInteractionId() {
        return personalInteractionId;
    }

    public void setPersonalInteractionId(Long personalInteractionId) {
        this.personalInteractionId = personalInteractionId;
    }

    public long getConnectionId() {
        return connectionId;
    }

    public void setConnectionId(long connectionId) {
        this.connectionId = connectionId;
    }

    @NotNull
    public String getFileUri() {
        return fileUri;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileUri(@NotNull String fileUri) {
        this.fileUri = fileUri;
    }

    @NotNull
    public String getFilePath() {
        return filePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilePath(@NotNull String filePath) {
        this.filePath = filePath;
    }

    public int getMediaType() {
        return mediaType;
    }

    public void setMediaType(int mediaType) {
        this.mediaType = mediaType;
    }

    public FileStatus getFileStatus() {
        return fileStatus;
    }

    public void setFileStatus(FileStatus fileStatus) {
        this.fileStatus = fileStatus;
    }

    @NotNull
    public java.util.Date getModifiedTime() {
        return modifiedTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModifiedTime(@NotNull java.util.Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @NotNull
    public String getFileName() {
        return fileName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileName(@NotNull String fileName) {
        this.fileName = fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Long getBytesTransfered() {
        return bytesTransfered;
    }

    public void setBytesTransfered(Long bytesTransfered) {
        this.bytesTransfered = bytesTransfered;
    }

}
