package com.aj.sendall.db.model;

import org.greenrobot.greendao.annotation.*;

import com.aj.sendall.db.enums.FileStatus;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSONAL_INTERACTION".
 */
@Entity
public class PersonalInteraction {

    @Id(autoincrement = true)
    private Long personalInteractionId;
    private Long connectionId;
    private String fileUri;
    private Integer mediaType;

    @Convert(converter = com.aj.sendall.db.converters.FileStatusToIntConverter.class, columnType = Integer.class)
    private FileStatus fileStatus;
    private java.util.Date modifiedTime;
    private String fileName;
    private String fileSize;

    @Generated
    public PersonalInteraction() {
    }

    public PersonalInteraction(Long personalInteractionId) {
        this.personalInteractionId = personalInteractionId;
    }

    @Generated
    public PersonalInteraction(Long personalInteractionId, Long connectionId, String fileUri, Integer mediaType, FileStatus fileStatus, java.util.Date modifiedTime, String fileName, String fileSize) {
        this.personalInteractionId = personalInteractionId;
        this.connectionId = connectionId;
        this.fileUri = fileUri;
        this.mediaType = mediaType;
        this.fileStatus = fileStatus;
        this.modifiedTime = modifiedTime;
        this.fileName = fileName;
        this.fileSize = fileSize;
    }

    public Long getPersonalInteractionId() {
        return personalInteractionId;
    }

    public void setPersonalInteractionId(Long personalInteractionId) {
        this.personalInteractionId = personalInteractionId;
    }

    public Long getConnectionId() {
        return connectionId;
    }

    public void setConnectionId(Long connectionId) {
        this.connectionId = connectionId;
    }

    public String getFileUri() {
        return fileUri;
    }

    public void setFileUri(String fileUri) {
        this.fileUri = fileUri;
    }

    public Integer getMediaType() {
        return mediaType;
    }

    public void setMediaType(Integer mediaType) {
        this.mediaType = mediaType;
    }

    public FileStatus getFileStatus() {
        return fileStatus;
    }

    public void setFileStatus(FileStatus fileStatus) {
        this.fileStatus = fileStatus;
    }

    public java.util.Date getModifiedTime() {
        return modifiedTime;
    }

    public void setModifiedTime(java.util.Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileSize() {
        return fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

}
